import { useMemo, useRef } from 'react';
import { format, isSaturday, isSunday, getDay } from 'date-fns';

const DAY_ABBREVS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

export default function EmployeeRosterModal({ employee, schedule, dates, contractName, periodLabel, onClose }) {
  const printRef = useRef();
  const empSchedule = schedule[employee.id] || {};

  const stats = useMemo(() => {
    const values = Object.values(empSchedule);
    return {
      totalDays: dates.length,
      daysWorked: values.filter(v => v !== 'off').length,
      daysOff: values.filter(v => v === 'off').length,
      eveningShifts: values.filter(v => v === '7/3').length,
      amShifts: values.filter(v => v === '3/7').length,
    };
  }, [empSchedule, dates]);

  const handlePrint = () => {
    const printContent = printRef.current;
    const win = window.open('', '_blank');
    win.document.write(`
      <html>
        <head>
          <title>Roster - ${employee.name}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 24px; color: #1a1a1a; }
            h1 { font-size: 20px; margin-bottom: 4px; }
            h2 { font-size: 14px; color: #666; margin-bottom: 20px; font-weight: normal; }
            .stats { display: flex; gap: 16px; margin-bottom: 20px; flex-wrap: wrap; }
            .stat-box { background: #f5f5f5; border-radius: 8px; padding: 10px 16px; text-align: center; min-width: 100px; }
            .stat-value { font-size: 22px; font-weight: bold; }
            .stat-label { font-size: 11px; color: #888; margin-top: 2px; }
            .stat-blue .stat-value { color: #1d4ed8; }
            .stat-green .stat-value { color: #15803d; }
            .stat-yellow .stat-value { color: #a16207; }
            .stat-purple .stat-value { color: #7e22ce; }
            .stat-indigo .stat-value { color: #4338ca; }
            table { border-collapse: collapse; width: 100%; margin-top: 16px; }
            th, td { border: 1px solid #ddd; padding: 6px 10px; text-align: center; font-size: 12px; }
            th { background: #f0f0f0; font-weight: 600; }
            .weekend { background: #eff6ff; }
            .off { background: #fef9c3; font-weight: 600; color: #a16207; }
            .off-weekend { background: #dcfce7; font-weight: 600; color: #15803d; }
            .shift-73 { color: #1d4ed8; }
            .shift-37 { color: #7e22ce; }
            .footer { margin-top: 24px; font-size: 11px; color: #999; border-top: 1px solid #ddd; padding-top: 12px; }
          </style>
        </head>
        <body>
          ${printContent.innerHTML}
          <div class="footer">
            Generated on ${format(new Date(), 'MMM dd, yyyy \'at\' h:mm a')} &mdash; Nu Home Janitorial Roster Manager
          </div>
        </body>
      </html>
    `);
    win.document.close();
    win.print();
  };

  const handleShare = async () => {
    const lines = [`Roster for ${employee.name}`, `${contractName} - ${periodLabel}`, ''];
    lines.push(`Days Worked: ${stats.daysWorked} | Days Off: ${stats.daysOff}`);
    lines.push(`Evening (7/3): ${stats.eveningShifts} | AM (3/7): ${stats.amShifts}`);
    lines.push('');
    lines.push('Schedule:');
    dates.forEach((date, idx) => {
      const val = empSchedule[idx] || '—';
      const dayName = DAY_ABBREVS[getDay(date)];
      const dateStr = format(date, 'MMM dd');
      const display = val === 'off' ? 'OFF' : val;
      lines.push(`  ${dayName} ${dateStr}: ${display}`);
    });
    lines.push('');
    lines.push(`Generated by Nu Home Janitorial Roster Manager`);

    const text = lines.join('\n');

    if (navigator.share) {
      try {
        await navigator.share({ title: `Roster - ${employee.name}`, text });
        return;
      } catch { /* user cancelled or not supported */ }
    }

    await navigator.clipboard.writeText(text);
    alert('Roster copied to clipboard! You can paste it into an email, WhatsApp, or any message.');
  };

  const isWeekend = (date) => isSaturday(date) || isSunday(date);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={onClose}>
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[90vh] flex flex-col" onClick={e => e.stopPropagation()}>
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200">
          <div>
            <h2 className="text-lg font-bold text-gray-900">{employee.name}</h2>
            <p className="text-sm text-gray-500">{contractName} &mdash; {periodLabel}</p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleShare}
              className="px-3 py-1.5 text-sm font-medium rounded-lg bg-green-50 text-green-700 border border-green-200 hover:bg-green-100 transition-colors"
            >
              Share / Copy
            </button>
            <button
              onClick={handlePrint}
              className="px-3 py-1.5 text-sm font-medium rounded-lg bg-blue-50 text-blue-700 border border-blue-200 hover:bg-blue-100 transition-colors"
            >
              Print
            </button>
            <button
              onClick={onClose}
              className="w-8 h-8 flex items-center justify-center rounded-lg text-gray-400 hover:bg-gray-100 hover:text-gray-600 transition-colors"
            >
              &times;
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="overflow-y-auto px-6 py-4 flex-1">
          <div ref={printRef}>
            <h1 style={{ display: 'none' }} className="print-only">{employee.name}</h1>
            <h2 style={{ display: 'none' }} className="print-only">{contractName} &mdash; {periodLabel}</h2>

            {/* Stats */}
            <div className="grid grid-cols-5 gap-3 mb-5">
              <div className="bg-blue-50 rounded-xl p-3 text-center">
                <div className="text-2xl font-bold text-blue-700">{stats.daysWorked}</div>
                <div className="text-[10px] text-blue-500 mt-0.5">Days Worked</div>
              </div>
              <div className="bg-yellow-50 rounded-xl p-3 text-center">
                <div className="text-2xl font-bold text-yellow-700">{stats.daysOff}</div>
                <div className="text-[10px] text-yellow-600 mt-0.5">Days Off</div>
              </div>
              <div className="bg-gray-50 rounded-xl p-3 text-center">
                <div className="text-2xl font-bold text-gray-700">{dates.length}</div>
                <div className="text-[10px] text-gray-500 mt-0.5">Total Days</div>
              </div>
              <div className="bg-indigo-50 rounded-xl p-3 text-center">
                <div className="text-2xl font-bold text-indigo-700">{stats.eveningShifts}</div>
                <div className="text-[10px] text-indigo-500 mt-0.5">Evening (7/3)</div>
              </div>
              <div className="bg-purple-50 rounded-xl p-3 text-center">
                <div className="text-2xl font-bold text-purple-700">{stats.amShifts}</div>
                <div className="text-[10px] text-purple-500 mt-0.5">AM (3/7)</div>
              </div>
            </div>

            {/* Schedule table */}
            <table className="w-full border-collapse text-sm">
              <thead>
                <tr className="bg-gray-50">
                  <th className="px-3 py-2 text-left text-xs font-semibold text-gray-600 border border-gray-200">Day</th>
                  <th className="px-3 py-2 text-left text-xs font-semibold text-gray-600 border border-gray-200">Date</th>
                  <th className="px-3 py-2 text-center text-xs font-semibold text-gray-600 border border-gray-200">Shift</th>
                </tr>
              </thead>
              <tbody>
                {dates.map((date, idx) => {
                  const value = empSchedule[idx] || '—';
                  const weekend = isWeekend(date);
                  const isOff = value === 'off';

                  return (
                    <tr
                      key={idx}
                      className={
                        isOff && weekend ? 'bg-green-50' :
                        isOff ? 'bg-yellow-50' :
                        weekend ? 'bg-blue-50/30' : ''
                      }
                    >
                      <td className="px-3 py-1.5 border border-gray-200 text-xs font-medium text-gray-600">
                        {DAY_ABBREVS[getDay(date)]}
                      </td>
                      <td className="px-3 py-1.5 border border-gray-200 text-xs text-gray-700">
                        {format(date, 'MMM dd, yyyy')}
                      </td>
                      <td className={`px-3 py-1.5 border border-gray-200 text-xs text-center font-medium ${
                        isOff ? 'text-yellow-700 font-semibold' :
                        value === '7/3' ? 'text-blue-700' :
                        value === '3/7' ? 'text-purple-700' : 'text-gray-500'
                      }`}>
                        {isOff ? 'OFF' : value}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}
